export const UPDATE_SEARCH_PARAMETERS = 'UPDATE_SEARCH_PARAMETERS';
export const RECEIVED_RESULTS = 'RECEIVED_RESULTS';
export const UPDATE_FORM_VALUE = 'UPDATE_FORM_VALUE';
export const SEARCH = 'SEARCH';
